
services:
  laravel:
    image: bitnami/laravel:latest
    container_name: laravel
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_myapp
      - DB_USERNAME=bn_myapp
      - DB_PASSWORD=bn_password  
    volumes:
      - ./my-project:/app
      - ./my-project/vendor:/app/vendor
    networks:
      database-net:
          ipv4_address: 172.21.21.10     

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secretpassword
      - MARIADB_DATABASE=bitnami_myapp
      - MARIADB_USER=bn_myapp
      - MARIADB_PASSWORD=bn_password
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      database-net:
          ipv4_address: 172.21.21.20    

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8443:80
    environment:
      - PMA_ARBITRARY=1    
    networks:
      database-net:
          ipv4_address: 172.21.21.30           

networks:
  database-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.21.0/24    





# volumes:
#   mariadb_data:



